extends RefCounted
const Gesture := preload("res://ui/world_gesture.gd")

static func run(check: Callable) -> void:
	var gesture := Gesture.new()
	var actions: Array[String] = []
	gesture.action_requested.connect(func(action: String, _value: Variant) -> void: actions.append(action))
	gesture.begin(Vector2.ZERO, 0, "create", false)
	gesture.advance(0.44)
	check.call(actions.is_empty(), "Hold does not create before its threshold")
	gesture.advance(0.02)
	gesture.release(Vector2.ZERO, 0)
	check.call(actions == ["create"], "Creation hold cannot also walk or confirm")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "create", false)
	gesture.move(Vector2(-50, 2), 0)
	gesture.advance(1.0)
	gesture.release(Vector2(-50, 2), 0)
	check.call(actions == ["camera_turn"], "Swipe cancels creation and walking")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "sheet", false)
	gesture.advance(0.46)
	gesture.release(Vector2.ZERO, 0)
	check.call(actions == ["edit"], "Sheet hold opens editing without confirming")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "sheet", false)
	gesture.release(Vector2.ZERO, 0)
	check.call(actions == ["walk"], "Short taps walk through the mirror")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "outline", true)
	gesture.move(Vector2(30, 0), 0)
	gesture.release(Vector2(30, 0), 0)
	check.call(actions.has("drag_end") and not actions.has("apply"), "Dragging the outline never confirms")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "outline", true)
	gesture.release(Vector2.ZERO, 1)
	check.call(gesture.active and actions.is_empty(), "Another finger cannot release a gesture")
	gesture.release(Vector2.ZERO, 0)
	check.call(actions == ["apply"], "A separate short outline tap confirms")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "sheet", true)
	gesture.release(Vector2.ZERO, 0)
	check.call(actions == ["apply"], "A separate short sheet tap confirms")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "outline", true)
	gesture.advance(0.6)
	gesture.release(Vector2.ZERO, 0)
	check.call(actions.is_empty(), "A long outline hold does not confirm")
	gesture.begin(Vector2.ZERO, 0, "sheet", true)
	gesture.move(Vector2(30, 0), 0)
	gesture.cancel()
	check.call(not gesture.active and actions.has("drag_end"), "Focus cancellation releases translation")
