extends RefCounted
const Gesture := preload("res://ui/world_gesture.gd")
const Grip := preload("res://ui/rotation_grip.gd")

static func run(check: Callable) -> void:
	var gesture := Gesture.new()
	var actions: Array[String] = []
	gesture.action_requested.connect(func(action: String, _value: Variant) -> void: actions.append(action))
	gesture.begin(Vector2.ZERO, 0, "create", false)
	gesture.advance(0.44)
	check.call(actions.is_empty(), "Hold does not create before its threshold")
	gesture.advance(0.02)
	gesture.release(Vector2.ZERO, 0)
	check.call(actions == ["create"], "Creation hold cannot also walk or confirm")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "create", false)
	gesture.move(Vector2(-50, 2), 0)
	gesture.advance(1.0)
	gesture.release(Vector2(-50, 2), 0)
	check.call(actions == ["camera_turn"], "Swipe cancels creation and walking")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "sheet", false)
	gesture.advance(0.46)
	gesture.release(Vector2.ZERO, 0)
	check.call(actions == ["edit"], "Sheet hold opens editing without confirming")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "sheet", false)
	gesture.release(Vector2.ZERO, 0)
	check.call(actions == ["walk"], "Short taps walk through the mirror")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "outline", true)
	gesture.move(Vector2(30, 0), 0)
	gesture.release(Vector2(30, 0), 0)
	check.call(actions.has("drag_end") and not actions.has("apply"), "Dragging the outline never confirms")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "outline", true)
	gesture.release(Vector2.ZERO, 1)
	check.call(gesture.active and actions.is_empty(), "Another finger cannot release a gesture")
	gesture.release(Vector2.ZERO, 0)
	check.call(actions == ["apply"], "A separate short outline tap confirms")
	actions.clear()
	gesture.begin(Vector2.ZERO, 0, "outline", true)
	gesture.advance(0.6)
	gesture.release(Vector2.ZERO, 0)
	check.call(actions.is_empty(), "A long outline hold does not confirm")
	gesture.begin(Vector2.ZERO, 0, "sheet", true)
	gesture.move(Vector2(30, 0), 0)
	gesture.cancel()
	check.call(not gesture.active and actions.has("drag_end"), "Focus cancellation releases translation")
	var grip := Grip.new()
	grip.size = Vector2(84, 84)
	var turns: Array[int] = []
	grip.action_requested.connect(func(value: int) -> void: turns.append(value))
	grip._pointer(Vector2(20, 42), true, 0)
	grip._drag(Vector2(46, 42))
	grip._drag(Vector2(76, 42))
	grip._finish(Vector2(76, 42))
	check.call(turns == [1], "A grip drag emits only one quarter turn")
	turns.clear()
	grip._pointer(Vector2(16, 42), true, 0)
	grip._finish(Vector2(16, 42))
	check.call(turns == [-1], "A directional grip end supports a short tap")
	turns.clear()
	grip._pointer(Vector2(16, 42), true, 0)
	grip._finish(Vector2(16, 78))
	check.call(turns.is_empty(), "Perpendicular grip movement does not become a tap")
	grip._pointer(Vector2(16, 42), true, 0)
	grip.cancel()
	grip._finish(Vector2(16, 42))
	check.call(turns.is_empty() and not grip.is_active(), "Cancelling a grip releases it without a turn")
	grip.free()
